try {
    let a;
    console.log(a.length);

} catch (e) {
    console.log("inside catch");
}

console.log('hii there');
